//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jhl.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int ID { get; set; }
        public string LogType { get; set; }
        public Nullable<System.DateTime> Loged { get; set; }
        public Nullable<int> LogedBy { get; set; }
        public string Detail { get; set; }
    
        public virtual User User { get; set; }
    }
}
